# Generated by Django 6.1.1 on 2026-09-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_favorite_content_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/episodes/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/movies/'),
        ),
    ]
